apiVersion: v1
kind: ConfigMap
metadata:
  name: parsers-config
  namespace: parsers-ns
data:
  hostname: highloadsaver
  kafka_addr: my-cluster-kafka-bootstrap.kafka.svc.cluster.local
  kafka_topic: 'data'
  kafka_partition: '0'