version: '3'
services:
  highloadparser:
    image: vynovikov/highloadparser:0.1
    ports:
      - 3000:3000
    environment:
      - KAFKA_HOSTNAME=kafka
      - KAFKA_PORT=9092
    depends_on:
      - kafka
  highloadsaver:
    image: vynovikov/highloadsaver:0.1
    environment:
      - HOSTNAME=highloadsaver
      - KAFKA_HOSTNAME=kafka
      - KAFKA_PORT=9092
    volumes:
      - "./results:/results"
    depends_on:
      - kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1