version: '3'
services:
  mainsrv:
    build: 
      context: .
    environment:
      - HOST=grpcsrv
      - PORT=3100
    ports:
      - "3000:3000"
    depends_on:
      - grpcsrv
      
  grpcsrv:
      build: 
        context: ../grpcSrv
      expose:
        - "3100"


