apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: parsers-ingress
  namespace: parsers-ns
spec:
  rules:
    - host: parsers.com
      http:
        paths:
          - pathType: Exact
            path: /
            backend:
              service:
                name: parsers-svc
                port: 
                  number: 80