apiVersion: apps/v1
kind: Deployment
metadata: 
  name: parsers-deployment
  namespace: parsers-ns
  labels:
    app: parsers-labels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parsers-selector
  template:
    metadata:
      labels:
        app: parsers-selector
    spec:
      containers:
        - name: parser
          image: vynovikov/highloadparser:0.36
          env:
            - name: KAFKA_ADDR
              valueFrom:
                configMapKeyRef:
                  name: parsers-config
                  key: kafka_addr            
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: parsers-config
                  key: kafka_topic
            - name: KAFKA_PARTITION
              valueFrom:
                configMapKeyRef:
                  name: parsers-config
                  key: kafka_partition
          ports:
            - containerPort: 3000
