apiVersion: apps/v1
kind: Deployment
metadata: 
  name: checker-deployment
  namespace:  checker-ns
  labels:
    app: checker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checker
  template:
    metadata:
      labels:
        app: checker
    spec:
      containers:
        - name: checker-name
          image: hwchiu/netutils
