apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.parsers.fullnameOverride }}-svc
  namespace: {{ .Values.parsers.fullnameOverride }}-ns
spec:
  selector:
    {{- include "highload-start.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.parsers.service.port}}
      targetPort: {{ .Values.parsers.service.targetPort}}