apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.savers.fullnameOverride }}-svc
  namespace: {{ .Values.savers.fullnameOverride }}-ns
  labels:
    {{- include "highload-start.labels" . | nindent 4}}
spec:
  selector:
    app: savers-selector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
