apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.savers.fullnameOverride }}-cm
  namespace: {{ .Values.savers.fullnameOverride }}-ns
  labels:
    {{- include "savers-chart.labels" . | nindent 4 }}
data:
  kafka_addr: {{ .Values.kafka.bootstrapURL }}
  kafka_topic_name: {{ .Values.kafka.topicName }}
